---
apiVersion: v1
kind: Service
metadata:
  name: webapp-v2-svc
  labels:
    application: k8s101
    version: v2
    tier: front
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: webapp
    version: v2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-v2
  labels:
    application: k8s101 
    version: v2
    tier: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
      version: v2
  template:
    metadata:
      labels:
        app: webapp
        version: v2
    spec:
      containers:
      - name: frontend
        image: registry.gitlab.com/f.chmainy/toremove/webapp:v2
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: myregcred
